### ISSUE TITLE
Create initial test set of target output, with accompanying genome data

### ISSUE THREAD

**Issue by widdowquinn** [pyani-plus/pyani-plus#1]
We need a standardised group of output targets/input files for developing the new Snakemake integration.

- a list of comparison outputs (provided to snakemake to initiate the workflow)
- a directory containing the input genome files (so that the workflow has inputs)
- reference outputs for the comparisons so that we can use test-driven development to confirm the comparisons work

NOTE: we are looking to use `pytest` for testing throughout development so it would be good to be compatible with this/use its features to help.

**Comment by kiepczi** [comment]
I have added the initial test sets for `Snakemake` integration to the repo under the branch `issue_1`. 

To facilitate easier development of `pyani-plus` and future testing and debugging, I have used the same test sets currently use in `pyani`. 

Within the `tests` directory, you can find the following:
```bash
├── test_input
│   └── anim
│       ├── NC_002696.fna
│       ├── NC_010338.fna
│       ├── NC_011916.fna
│       └── NC_014100.fna
├── test_pyani_plus_output
│   └── anim
│       ├── matrix_aln_lengths_1.tab
│       ├── matrix_coverage_1.tab
│       ├── matrix_hadamard_1.tab
│       ├── matrix_identity_1.tab
│       └── matrix_sim_errors_1.tab
├── test_reference_output
│   └── anim
│       └── deltadir_result.csv
├── test_snakemake_anim_workflow.py
└── test_targets
    └── anim
        ├── NC_002696_vs_NC_010338.filter
        ├── NC_002696_vs_NC_011916.filter
        ├── NC_002696_vs_NC_014100.filter
        ├── NC_010338_vs_NC_002696.filter
        ├── NC_010338_vs_NC_011916.filter
        ├── NC_010338_vs_NC_014100.filter
        ├── NC_011916_vs_NC_002696.filter
        ├── NC_011916_vs_NC_010338.filter
        ├── NC_011916_vs_NC_014100.filter
        ├── NC_014100_vs_NC_002696.filter
        ├── NC_014100_vs_NC_010338.filter
        └── NC_014100_vs_NC_011916.filter
```

Input genome files are located in `test_input/anim`, and target output (.filter) files are located in `test_targets/anim`. Additionally, I have included the current matrices provided by `pyani` for future testing. Eg. whether the future workflow and pairwise comparisons are executed correctly. 

`pytest` will be used to test the `Snakemake` workflow, and I have already written one test as provided in `test_snakemake_anim_workflow.py`... but, I will follow on this in #2.

**Comment by kiepczi** [comment]
Changes have been made to restructure the `tests` directory, aiming for better organisation and readiness for future implementations.

The current layout of the `test` directory is as follows:

```
├── conftest.py
├── fixtures
│   ├── anim
│   │   ├── dataframes
│   │   │   ├── deltadir_result.csv
│   │   │   └── matrices
│   │   └── targets
│   │       ├── delta
│   │       └── filter
│   ├── sequences
├── generate_fixtures
│   └── generate_target_anim_files.sh
├── nucmer_delta_output
├── nucmer_filter_output
├── fastani_output
└── snakemake
    ├── test_snakemake_anim_files.py
    └── test_snakemake_anim_workflow.py
```

The `fixture` directory now contains separate subdirectories for distinct methods (e.g., `anim`, `fastani`, etc.). Each method subdirectory will contain target files, expected outputs, and data frames with expected results.

Additionally, the fixture directory now contains a `sequence` subdirectory for keeping all genome files used in tests or fixture generation.

The test directory has further subdivisions:
- `generate_fixtures`: This subdirectory contains scripts used in generating target files.
- `snakemake`: Here, pytest scripts are stored for testing workflows.
- `conftest.py`: A pytest configuration file.
- Other method-specific output files generated during workflow testing.
