### ISSUE TITLE
Port ANIb code from legacy pyANI to compute and log identity etc

### ISSUE THREAD

**Issue by peterjc** [pyani-plus/pyani-plus#102]
This will build on #13 which handles the query FASTA file fragmentation, subject file BLAST database building, and actually running NCBI BLAST to compare the fragmented query to the subject database.

This issues is to:

* Parse the tabular output from ``blastn`` to compute the identity etc as per ANIb
* Use that to define another private-cli function to log an ANIb comparison (see the fastANI code added initially in 7b524ed5921612f01279cf26ea4052d926ef08d9 for this approach)
* Extend the snakemake workflow test to setup the DB and then call this new functionality (see the fastANI test code https://github.com/pyani-plus/pyani-plus/blob/main/tests/snakemake/test_snakemake_fastani_workflow.py for this)

**Comment by peterjc** [comment]
Related to this is generating reference values to test against, but it seems the pyANI v0.3 master branch for ``subcmd_anib.py`` and ``subcmd_aniblastall.py`` are full of ``NotImplementedError`` stubs.

**Comment by widdowquinn** [comment]
Yes - sorry about that. It was a thing to be done earlier in the project but that wasn't reached :(

Example code is in the `version_0_2` branch of old `pyani', e.g. https://github.com/widdowquinn/pyani/blob/version_0_2/pyani/anib.py

**Comment by peterjc** [comment]
Success with something based on ``average_nucleotide_identity.py -m ANIb -i . -o output -v -l ANIb.log --force`` giving ``ANIb_percentage_identity.tab`` etc:

```
                    OP073605            MGV-GENOME-0266457  MGV-GENOME-0264574
OP073605            1.0                 0.9946458974358975  0.9992984615384616
MGV-GENOME-0266457  0.99467             1.0                 0.9944781578947369
MGV-GENOME-0264574  0.9993184615384614  0.9945938461538463  1.0
```

Note to self: pyANI v0.2 had a different main script name than v0.3
