### ISSUE TITLE
Create initial `snakemake` workflow for ANIb 

### ISSUE THREAD

**Issue by kiepczi** [pyani-plus/pyani-plus#13]
To create initial `snakemake` workflow for `ANIb` method, we need to do the following:

1. Update the Makefiles to include the installation of `blast`.

2. Write Initial Workflow to Generate Appropriate Files. 

3. Create Test Set of Target Outputs.

4. Test the Workflow with `pytest`.

**Comment by peterjc** [comment]
Quoting from https://github.com/pyani-plus/pyani-plus/pull/48#issuecomment-2277958288

> My opinion is that we should drop blast-legacy for good with this iteration of pyani. One reason for hanging on to it was to confirm consistency with older ANIb-based tools (e.g. JSpecies), but that doesn't seem so compelling at this point.

**Comment by peterjc** [comment]
I started with just the genome fragmentation on #85, but have moved on to trying to run this within snakemake now...

**Comment by peterjc** [comment]
My work on PR #85 is now part of PR #101, which will close this issue.

I have opened issue #102 for the next step, actually parsing the output generated via snakemake to compute the ANIb identity and log this in the DB.
