### ISSUE TITLE
Ensure all intermediate files follow the `<query>_vs_<subject>.<extension>` format

### ISSUE THREAD

**Issue by kiepczi** [pyani-plus/pyani-plus#135]
Currently, `pyani-plus` uses different third-party software to compare genomes, and each software handles the order of genomes differently. For example, in `BLAST`, the order is `<query>` then `<subject>`, while in `nucmer`, the order is `<subject>` then `<query>`. As a result, intermediate files are saved in a format that reflects the parameters' order used by each software.

 For consistency, @peterjc and I agreed that all intermediate files should have the same naming format of `<query>_vs_<subject>.<extension>` regardless of the software used (as disussed in #129).

**Comment by peterjc** [comment]
Quoting https://github.com/pyani-plus/pyani-plus/blob/main/pyani_plus/workflows/snakemake_anib.smk the naming for ANIb is ``<query>_vs_<subject>.<extension>``:

```
        {params.blastn} -query {wildcards.outdir}/{wildcards.genomeA}-fragments.fna \
            -db {wildcards.outdir}/{wildcards.genomeB} -out {output} -task blastn \
            -outfmt '6 qseqid sseqid length mismatch pident nident qlen slen \
                     qstart qend sstart send positive ppos gaps' \
            -xdrop_gap_final 150 -dust no -evalue 1e-15 -max_target_seqs 1 
```

Likewise from https://github.com/pyani-plus/pyani-plus/blob/main/pyani_plus/workflows/snakemake_anib.smk for fastANI:

```
        {params.fastani} -q {input.genomeA} -r {input.genomeB} \
            -o {wildcards.outdir}/{wildcards.genomeA}_vs_{wildcards.genomeB}.fastani \
            --fragLen {params.fragLen} -k {params.kmerSize} --minFraction {params.minFrac}
```

We can make this more explicit by changing the snakemake wildcards from ``genomeA`` and ``genomeB`` to ``query`` and ``subject`` instead?

**Comment by kiepczi** [comment]
Sorry, I wasn't clear enough. That's what I meant. 
I will also need to change `aniM` and `dnadiff` method fixtures too.

**Comment by peterjc** [comment]
Yes - the inconsistency is in ANIm where we use:

```
{params.nucmer} -p {wildcards.outdir}/{wildcards.genomeA}_vs_{wildcards.genomeB} --mum {input.genomeA} {input.genomeB}
```

and dnadiff:

```
{params.nucmer} -p {wildcards.outdir}/{wildcards.genomeA}_vs_{wildcards.genomeB} --maxmatch {input.genomeA} {input.genomeB}
```

This is because nucmer wants the arguments in this order:

```
$ nucmer --help 2>&1 | head -n 3

  USAGE: nucmer  [options]  <Reference>  <Query>

```
