### ISSUE TITLE
Investigate `snakemake` workflow execution on SLURM cluster

### ISSUE THREAD

**Issue by kiepczi** [pyani-plus/pyani-plus#14]
The current `snakemake` workflows were developed on local machines. We need to investigate whether these workflows can be executed on SLURM clusters.

The following aspects should be investigated at this stage:

1. Can all workflows be executed without any errors on SLURM? If not, we need to investigate the causes of any errors and identify potential fixes.
2. Does SLURM successfully distribute jobs?
3. Are all expected files generated?
4. Is the content of the generated files as expected? For example, compare the content of files generated on SLURM with those generated on local machines.

**Comment by kiepczi** [comment]
I'm currently working on this in branch `issue_14`. 

> 1. Can all workflows be executed without any errors on SLURM? If not, we need to investigate the causes of any errors and identify potential fixes.
> 3. Are all expected files generated?
> 4. Is the content of the generated files as expected? For example, compare the content of files generated on SLURM with those generated on local machines.

For the above, I've written pytest tests to validate the current workflows (anim, fastani, and dnadiff). The workflows were executed on SLURM with no errors (see below), and all tests passed, indicating that all expected files were generated and the content of these files is the same as when running on my local machine (macOS).

```bash
===================================================================================
SLURM Job ID:            11289534
Submit time:             Fri May 24 16:34:52 BST 2024 (Unix Epoch time: 1716564892)
Start time:              Fri May 24 16:34:52 BST 2024 (Unix Epoch time: 1716564892)
No. nodes:               1
No. tasks:               12
Job name:                snakemake_test
Account:                 pritchard-grxiv
QoS:                     priority
Partition (queue):       dev
Submit directory:        /users/xmb20196/pyani_plus
Script name:             /users/xmb20196/pyani_plus/slurm_testing.sh
Master node:             dev1
Nodes used:              dev1
Task distribution:       
===================================================================================

============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.2.1, pluggy-1.5.0 -- /users/xmb20196/.conda/envs/pyani_plus_smk/bin/python
cachedir: .pytest_cache
rootdir: /users/xmb20196/pyani_plus
configfile: pyproject.toml
plugins: cov-5.0.0
collecting ... collected 6 items

tests/snakemake/test_snakemake_slurm.py::test_snakemake_rule_delta_slurm PASSED [ 16%]
tests/snakemake/test_snakemake_slurm.py::test_snakemake_rule_filter_slurm PASSED [ 33%]
tests/snakemake/test_snakemake_slurm.py::test_snakemake_rule_fastani_slurm PASSED [ 50%]
tests/snakemake/test_snakemake_slurm.py::test_dnadiff_rule_delta_slurm PASSED [ 66%]
tests/snakemake/test_snakemake_slurm.py::test_dnadiff_rule_filter_slurm PASSED [ 83%]
tests/snakemake/test_snakemake_slurm.py::test_dnadiff_rule_show_diff_slurm PASSED [100%]

=============================== warnings summary ===============================
tests/snakemake/test_snakemake_slurm.py::test_snakemake_rule_delta_slurm
  /users/xmb20196/.conda/envs/pyani_plus_smk/lib/python3.11/site-packages/stopit/__init__.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================== 6 passed, 1 warning in 117.14s (0:01:57) ===================
===================================================================================
SLURM job 11289534 ended:     Fri May 24 16:36:58 BST 2024 (Unix Epoch time: 1716565018)
This is an estimated end time using the 'date' command from node dev1.hpc.strath.ac.uk
For accurate timings, use 'sacct -j 11289534 -X --format=Submit,Start,End,Elapsed'
======================================================================================
```

> 2. Does SLURM successfully distribute jobs?
As per our last conversation, it was agreed that for now we can manually monitor the queue to check if jobs are scheduled through SLURM. I can confirm that this is the case, see the following:

```bash
(pyani_plus_smk) [xmb20196@archie-t pyani_plus]$ sqme
   JOBID PARTITION       QOS PRIORITY            NAME     USER ST          START_TIME        TIME   TIME_LEFT  NODES CPUS NODELIST(REASON)
11289499       dev  priority     2022  snakemake_test xmb20196  R 2024-05-24T15:27:44        0:13       29:47      1   40 dev1
(pyani_plus_smk) [xmb20196@archie-t pyani_plus]$ 
```

**Comment by widdowquinn** [comment]
This looks like it is working for now, and we can close this.

**Comment by peterjc** [comment]
FYI, the warning from ``stopit`` (something ``snakemake`` uses internally) would be fixed by this pull request or similar: https://github.com/glenfant/stopit/pull/30
