### ISSUE TITLE
Add resume command to public CLI

### ISSUE THREAD

**Issue by peterjc** [pyani-plus/pyani-plus#154]
Any of the methods will take a non-trivial time to run, so there is a chance of interruption. Perhaps more so with a cluster.

The database design avoids recomputing any pairwise ANI previously logged, so starting a new run will effectively resume (assuming same command is executed, via the shell history perhaps).

I am considering a new resume command taking only the database path and optionally run-id, defaulting to the most recent run. This will then check if any comparisons are missing, and if so run those after checking the command line dependency version matches that from the old run.

**Comment by widdowquinn** [comment]
I like this idea - I'm curious about how it might cascade with runs that refer to other incomplete runs… it's probably more straightforward that I imagine, just now.

**Comment by peterjc** [comment]
Currently if you did the following (where all three examples have the same configuration and thus will share comparisons):

1. Ran ``pyani-plus anib --database demo.db --create-db --name "Run 1" my_genomes/`` but aborted it almost immediately.
2. Ran ``pyani-plus anib --database demo.db --name "Run 2" my_genomes/`` and let it partly complete, and then abort.
3. Run ``pyani-plus list-runs --database demo.db`` will show both run 1 and run 2 have been partially completed.
4. Run ``pyani-plus anib --database demo.db --name "Run 3" my_genomes/`` and let it finish
5. Run ``pyani-plus list-runs --database demo.db`` will show all the runs are complete, but only "Run 3" will say this in its status column.

New plan:

1. Ran ``pyani-plus anib --database demo.db --create-db --name "Run 1" my_genomes/`` but aborted it almost immediately.
2. Run ``pyani-plus resume --database demo.db`` and let it partly complete then abort
3. Run ``pyani-plus list-runs --database demo.db`` will show only run 1 exists and has been partially completed.
4. Run ``pyani-plus resume --database demo.db`` and let it finish
5. Run ``pyani-plus list-runs --database demo.db`` will show just "Run 1" and it will completed in its status column.

**Comment by peterjc** [comment]
I have this working with one caveat - it needs to know the input FASTA directory name. It makes sense to me to record this in the run table...
