### ISSUE TITLE
ANIm should toggle between mum (default) and maxmatch, and record this configuration

### ISSUE THREAD

**Issue by peterjc** [pyani-plus/pyani-plus#164]
See #160, currently the ANIm method is hard coded to use the mum method, and the maxmatch field in the database is unused. It should be possible at the command line to run the workflow with nucmer's maxmatch mode instead.

To be decided: Should we keep the optional boolean field in the database (which only makes sense for mumer based tools), or replace it with something else like a string "mode" field? Here that would be mode="mum" (default) or mode="maxmatch" respectively for ANIm.

**Comment by widdowquinn** [comment]
I like the idea of a `--mode` option, especially as it could allow the user to specify multiple options in a syntax like `opt1,opt2,opt3` where several configuration options are available. I like that it could simplify database representation.

Pragmatically we'll need to take care to avoid incompatible options, if we offer this route. `mum` and `maxmatch` (and `maxreference`, not that we've offered it before) are mutually exclusive. There are likely other similar examples but none are springing to mind just now.

We'd also need to take care with option order if querying the database: "opt1,opt2,opt3" expresses but the same thing as, but is not identical to, "opt1,opt3,opt2" Or we could just not provide for a search on that field, to sidestep the issue - but still allow us to report the run `mode` options ;)
