### ISSUE TITLE
Write module to parse `dnadiff` output

### ISSUE THREAD

**Issue by kiepczi** [pyani-plus/pyani-plus#17]
After developing the initial workflow for the `dnadiff` method #12, we need to ensure that we can reproduce the `AlignedBases` value provided by `dnadiff`.

To achieve this, we should:
- Write a module to parse all files generated by the Snakemake workflows for the `dnadiff` method.
- Generate a test set of expected output using `dnadiff`.
- Use `pytest` to compare the expected output with the output provided by the module.

**Comment by kiepczi** [comment]
I started working on this under the `issue_17` branch. 

So far, I have written functions to parse `.mcoords` and `.rdiff` files. The code still requires testing and few tweaks.

**Comment by kiepczi** [comment]
Should we close this issue since parsing of `dnadiff` output was merged with #126?

**Comment by peterjc** [comment]
Yes, and #133 will cover the final steps of getting this into the DB.
