### ISSUE TITLE
Report nulls (failed comparisons) in list-runs table?

### ISSUE THREAD

**Issue by peterjc** [pyani-plus/pyani-plus#203]
With the work for #140, we record Null entries in the DB for failed comparisons. It would be nice to report these in the ``pyani-plus list-runs ...`` output.

e.g. Here I was exploring k-mer size and scaling with sourmash on a small set of disparate genomes, often only getting the 6 self-identities alone:

<img width="1512" alt="Screenshot 2024-12-04 at 21 31 38" src="https://github.com/user-attachments/assets/341f5ed1-051b-4630-bb70-e38287eb7c16">

Or here, trying to reproduce a bug reported against old pyANI which looks to be down to a modest number of outlier sequences:

<img width="1495" alt="Screenshot 2024-12-04 at 21 31 55" src="https://github.com/user-attachments/assets/01f370fd-2a6e-4af2-aa13-1521275cfa6d">

This proof of principle was done with the following diff, but would separate columns be better? e.g. Number of good (non-null), bad (failed and null recorded), or missing (pending)?

<details>

```console
❯ git diff                             
diff --git a/pyani_plus/public_cli.py b/pyani_plus/public_cli.py
index 4465d1b..a2a825d 100644
--- a/pyani_plus/public_cli.py
+++ b/pyani_plus/public_cli.py
@@ -798,13 +798,21 @@ def list_runs(
         conf = run.configuration
         n = run.genomes.count()
         done = run.comparisons().count()
-        comparison_summary = f"{done}/{n**2}={n}²"
+        # Using is None does not work as expected, must use == None
+        nulls = run.comparisons().where(db_orm.Comparison.identity == None).count()
         if done == 0:
-            comparison_summary = Text(comparison_summary, style="red")
-        elif done != n**2:
-            comparison_summary = Text(comparison_summary, style="yellow")
+            main = "red"
+        elif done == n**2:
+            main = "green"
         else:
-            comparison_summary = Text(comparison_summary, style="green")
+            main = "yellow"
+        if nulls:
+            comparison_summary = Text(f"{nulls} null", style="red") + Text(
+                f" + {done-nulls}/{n**2}={n}²", style=main
+            )
+        else:
+            comparison_summary = Text(f"{done}/{n**2}={n}²", style=main)
+
         table.add_row(
             str(run.run_id),
             str(run.date.date()),

```

</details>

**Comment by peterjc** [comment]
Using four columns (Done, Null, Miss, Total), although perhaps "Fail" rather than "Null" would be clearer?:

<img width="1640" alt="Screenshot 2024-12-05 at 10 16 53" src="https://github.com/user-attachments/assets/00a8227c-edfc-4fe7-bdcf-4b59b64dbca3">
<img width="1552" alt="Screenshot 2024-12-05 at 10 16 40" src="https://github.com/user-attachments/assets/861b7870-aef0-4298-913e-700475d4a778">

Code:

<details>

```console
❯ git diff
diff --git a/pyani_plus/public_cli.py b/pyani_plus/public_cli.py
index 4465d1b..6ba406c 100644
--- a/pyani_plus/public_cli.py
+++ b/pyani_plus/public_cli.py
@@ -789,7 +789,10 @@ def list_runs(
     table.add_column("ID", justify="right", no_wrap=True)
     table.add_column("Date")
     table.add_column("Method")
-    table.add_column(Text("Comparisons", justify="left"), justify="right", no_wrap=True)
+    table.add_column(Text("Done", justify="left"), justify="right", no_wrap=True)
+    table.add_column(Text("Null", justify="left"), justify="right", no_wrap=True)
+    table.add_column(Text("Miss", justify="left"), justify="right", no_wrap=True)
+    table.add_column(Text("Total", justify="left"), justify="right", no_wrap=True)
     table.add_column("Status")
     table.add_column("Name")
     # Would be nice to report {conf.program} {conf.version} too,
@@ -797,19 +800,21 @@ def list_runs(
     for run in runs:
         conf = run.configuration
         n = run.genomes.count()
+        total = n**2
         done = run.comparisons().count()
-        comparison_summary = f"{done}/{n**2}={n}²"
-        if done == 0:
-            comparison_summary = Text(comparison_summary, style="red")
-        elif done != n**2:
-            comparison_summary = Text(comparison_summary, style="yellow")
-        else:
-            comparison_summary = Text(comparison_summary, style="green")
+        # Using is None does not work as expected, must use == None
+        nulls = run.comparisons().where(db_orm.Comparison.identity == None).count()
         table.add_row(
             str(run.run_id),
             str(run.date.date()),
             conf.method,
-            comparison_summary,
+            Text(
+                f"{done - nulls}",
+                style="green" if done == total and not nulls else "yellow",
+            ),
+            Text(f"{nulls}", style="red" if nulls else "green"),
+            Text(f"{total - done}", style="yellow" if done < total else "green"),
+            f"{n**2}={n}²",
             run.status,
             run.name,
         )


```

</details>

**Comment by kiepczi** [comment]
> Using four columns (Done, Null, Miss, Total), although perhaps "Fail" rather than "Null" would be clearer?:

I think `NULL` and `Fail` could be two different things. My first instinct when seeing `Fail` would be that the analysis for said genomes failed for reasons other than simply finding no alignments, such as termination of the program, corrupted files, etc. I think calling something a 'fail' could represent this kind of issue, while `NULL` could represent comparisons that completed but found no alignments. What is your opinion on this?

When it comes to the styles, I like both. I find the second one (more columns) more intuitive, but the first one (more wordy) looks neater in the presentation style. Personally, I would lean towards more columns, as I prefer things that are more intuitive, but I can see how this can be a matter of personal preference.

**Comment by peterjc** [comment]
Leighton and I were also torn between the two styles. So a slight preference for the multiple-column approach. I can turn that into a pull request then.

You're right "Fail" might suggest a run-time error or the like, while for us "Null" has the different meaning of no valid alignment.

Leighton and I also talked about "Miss" being a little unclear, it is short for "Missing". I also considered "Pending" but couldn't come up with another short name to keep the column narrow.

We might use "OK" for the "Done" column, but it makes little difference given typical counts - and I liked the symmetry of 4-letter column names.

**Comment by kiepczi** [comment]
I guess the more columns we add, the more complicated it becomes. We could either keep it simple and only report the analyses that are done, failed, or resulted in NULL, so that end users can figure out on their own how many pending comparisons are still left.

If we, however, decide to add a column for the number of pending comparisons, perhaps we could use a column named TBD (to be determined) or Q (for queue).

**Comment by peterjc** [comment]
Note right now we don't have any _direct_ way to tell pending comparisons from failed comparisons - the later don't get record in the DB.

Using "Q" for pending or missing jobs is neat - but it only makes sense to call them queued if the run is actually still running. Using "TBD" is better, but is it obvious enough?

I suppose we can look at the "status" column, which IIRC will be "Done" if the run completed normally and "Running" if the computation started. A top level error handler could change this to "Failed", but even so if the OS kills pyani-plus it may never get to log that.
