### ISSUE TITLE
Add module that checks for complete paths to executables

### ISSUE THREAD

**Issue by widdowquinn** [pyani-plus/pyani-plus#32]
## Summary:

For a range of reasons, including security and good practice/logging, it is desirable to have a module that, for each third-party application which will be called from the command-line, checks for a viable `$PATH` to that application and makes it available within pyani-plus.

The internal variables providing these paths can then be used in, for example, `subprocess.run()` commands in target fixture-generating scripts. If no `$PATH` is found we can prompt the user to install a missing tool.

## Description:

See [`dependencies.py`](https://github.com/widdowquinn/pyani/blob/master/pyani/dependencies.py) and related code in the original `pyani` repo for examples of how this can be done.

What I'm envisioning ATM is a module, e.g. `pyani-plus.dependencies` where we can get the path to - say - `nucmer` with something like

```python
from pyani-plus import dependencies

print(dependencies.nucmer_path)
print(dependencies.nucmer_version)
```

and have the underlying code return the appropriate `Path` or `str` object. Then, when running `nucmer` we'd replace the string that _assumes_ nucmer is in the `$PATH` with, say the `nucmer_path` variable. I think this should also apply within the snakemake workflows, but I'm not 100% sure how that looks, right now.

**Comment by peterjc** [comment]
See also https://github.com/peterjc/thapbi-pict/blob/master/thapbi_pict/versions.py where I have snippets of code to get the version of command line tools (e.g. https://github.com/peterjc/thapbi-pict/blob/v1.0.13/thapbi_pict/versions.py handles NCBI BLAST+ binaries).
