### ISSUE TITLE
By default unlock snakemake working directories

### ISSUE THREAD

**Issue by widdowquinn** [pyani-plus/pyani-plus#33]
## Summary:

If snakemake is halted during a run (e.g. cancelled tests) it can leave the working directory in a locked state. This prevents future tests from passing.

The solution to this is to add `dag_api.unlock()` ahead of the `dag_api.execute_workflow()` call in the interface to the snakemake workflow (i.e. in the `run_workflow()` function). I can't see a reason not to do this by default.

**Comment by widdowquinn** [comment]
If #18 involves having a single `run_workflow()` function/method, then we may need to only do this once, in that code block.

**Comment by kiepczi** [comment]
> If #18 involves having a single `run_workflow()` function/method, then we may need to only do this once, in that code block.

I have added changes to the snakemake runner module. As this was in some way related to #18, I have been working on this under branch `issue_18`.
