### ISSUE TITLE
Improve Test Naming Schemes and Documentation

### ISSUE THREAD

**Issue by kiepczi** [pyani-plus/pyani-plus#34]
The current test suite is confusing due to inconsistent naming schemes and a lack of documentation explaining the purpose of each test. To address this issue, we need to:

- Update docstrings for all test functions to provide clear explanations of their purpose and functionality.
- Remove redundant elements from test names, such as changing `test_dnadiff_rule_filter` to `test_rule_filter`.
- Add more documentation to workflows to explain the necessity of each rule.
- Explain the process and methodology of how and why tests are carried out.

**Comment by kiepczi** [comment]
As @peterjc spotted, there were unused fixtures in the test_snakemake_slurm.py file (see #54). It might be worth checking other tests as well, if this hasn't been done already, to ensure that the same issue doesn't exist elsewhere.

**Comment by peterjc** [comment]
We also have some duplication of function names between test modules:

```
$ pytest --collect-only
==================== test session starts =====================
platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/pjacock/repositories/pyani-plus
configfile: pyproject.toml
plugins: cov-5.0.0, xdist-3.6.1
collected 13 items                                           

<Dir pyani-plus>
  <Package tests>
    <Package snakemake>
      <Module test_snakemake_anim_workflow.py>
        <Function test_snakemake_rule_filter>
        <Function test_snakemake_rule_delta>
      <Module test_snakemake_dnadiff_workflow.py>
        <Function test_snakemake_rule_delta>
        <Function test_snakemake_rule_filter>
        <Function test_snakemake_rule_show_diff>
        <Function test_snakemake_rule_show_coords>
      <Module test_snakemake_fastani_workflow.py>
        <Function test_snakemake_rule_fastani>
      <Module test_snakemake_slurm.py>
        <Function test_snakemake_rule_delta_slurm>
        <Function test_snakemake_rule_filter_slurm>
        <Function test_snakemake_rule_fastani_slurm>
        <Function test_dnadiff_rule_delta_slurm>
        <Function test_dnadiff_rule_filter_slurm>
        <Function test_dnadiff_rule_show_diff_slurm>

================ 13 tests collected in 0.13s =================
```

e.g. Two of ``test_snakemake_rule_filter`` (for anim and for dnadiff).

This makes it harder to test a specific methods, for example ``pytest -v test_snakemake_rule_filter`` would get both with that name plus ``test_snakemake_rule_filter_slurm`` as well. That make have an easy solution though?

So I wouldn't drop the method name - rather I would try to use it more consistently.

I'm not sure about ``snakemake`` and ``rule`` being used everywhere, but that likely reflects the current test coverage?

**Comment by kiepczi** [comment]
I was just about to mention that we had a meeting with you (@widdowquinn) about this before @peterjc started. We both agreed that the naming of the tests could be improved to reduce redundancy.

One thing to keep in mind is that we need to test the rule delta and filter separately for aniM and dandiff, as the parameters differ between the two ANI methods. Additionally, for dandiff, we have other rules that rely on the output of rule filter. That's why we agreed on having separate workflows for dnadiff and aniM, even though some rules are somewhat redundant.

**Comment by peterjc** [comment]
What is the rational for the ``test_snakemake_slurm.py`` file? Looking at fastani to start with, it seems to duplicate the other test.

I'm looking at the two tests for ``snakemake_fastani.smk`` workflow. This in Module ``test_snakemake_slurm.py`` Function ``test_snakemake_rule_fastani_slurm``:

```python
@pytest.mark.slurm()
def test_snakemake_rule_fastani_slurm(
    fastani_targets_slurm: list[str],
    fastani_targets_slurm_outdir: Path,
    config_fastani_args: dict,
    fastani_targets_indir: Path,
    tmp_path: str,
) -> None:
    """Test fastANI snakemake wrapper.

    Checks that the fastANI rule in the fastANI snakemake wrapper gives the
    expected output.
    """
    # Remove the output directory to force re-running the snakemake rule
    shutil.rmtree(fastani_targets_slurm_outdir, ignore_errors=True)

    # Run snakemake wrapper
    runner = snakemake_scheduler.SnakemakeRunner("snakemake_fastani.smk")
    runner.run_workflow(
        fastani_targets_slurm, config_fastani_args, workdir=Path(tmp_path)
    )

    # Check output against target fixtures
    for fname in fastani_targets_slurm:
        assert compare_fastani_files(  # noqa: S101
            fastani_targets_indir / fname,
            fastani_targets_slurm_outdir / fname,
        )
```

This is near identical to the version in Module ``test_snakemake_fastani_workflow.py`` Function ``test_snakemake_rule_fastani``:

```python
def test_snakemake_rule_fastani(
    fastani_targets: list[str],
    fastani_targets_outdir: Path,
    config_fastani_args: dict,
    fastani_targets_indir: Path,
    tmp_path: str,
) -> None:
    """Test fastANI snakemake wrapper.

    Checks that the fastANI rule in the fastANI snakemake wrapper gives the
    expected output.
    """
    # Remove the output directory to force re-running the snakemake rule
    shutil.rmtree(fastani_targets_outdir, ignore_errors=True)

    # Run snakemake wrapper
    runner = snakemake_scheduler.SnakemakeRunner("snakemake_fastani.smk")

    runner.run_workflow(fastani_targets, config_fastani_args, workdir=Path(tmp_path))

    # Check output against target fixtures
    for fname in fastani_targets:
        assert compare_fastani_files(  # noqa: S101
            fastani_targets_indir / fname,
            fastani_targets_outdir / fname,
        )
```

To my eye they differ only in:

* the first fixture argument to the runner ``fastani_targets_slurm`` vs ``fastani_targets``, which boils down to a different output path (one with slurm at the end)
* the definition of local fixture ``config_fastani_args`` also only differs in the output path


Are these two not practically identical?

(Assuming there is meant to be a difference I've overlooked, we can at least look at defining the helper function ``compare_fastani_files`` centrally - we have two slightly different versions right now)

**Comment by kiepczi** [comment]
I'm not sure what I was thinking at the time (and was probably wrong) when writing the tests for checking how it executes on Slurm and why I did them separately, as they are the same.

It might be worth removing them from the repo. If we want to test how pyani behaves on Slurm, we can always run the usual set of tests. Right?

**Comment by peterjc** [comment]
Ah. That would make sense.

According to https://snakemake.readthedocs.io/en/v7.20.0/executing/cluster.html we'd use ``snakemake --slurm ...`` to run with SLURM, in which case the test scripts can do this (e.g. with and without SLURM).

So we can probably revert https://github.com/pyani-plus/pyani-plus/pull/52 and drop ``test_snakemake_slurm.py`` ?

**Comment by kiepczi** [comment]
After a few minutes of reflection, I think I wrote a separate set of `pytests` to test on `slurm` (I now realise it was pointless) and I never intended to merge them into the `main` branch. 

I think you're right; we can revert #52.

**Comment by peterjc** [comment]
One meaningful change aside the output paths in ``test_snakemake_slurm.py``, was bumping the cores from 8 to 12 in the job configurations for the SLURM version. Those values will interact with using ``pytest -n ...`` as per discussion on #51/#60.

**Comment by peterjc** [comment]
Current list of test modules and functions:

```
$ pytest --collect-only
===================== test session starts ======================
platform darwin -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /Users/pc40583/repositories/pyani-plus
configfile: pyproject.toml
plugins: cov-5.0.0, xdist-3.6.1
collected 17 items                                             

<Dir pyani-plus>
  <Package tests>
    <Package snakemake>
      <Module test_snakemake_anim_workflow.py>
        <Function test_snakemake_rule_filter>
        <Function test_snakemake_rule_delta>
      <Module test_snakemake_dnadiff_workflow.py>
        <Function test_snakemake_rule_delta>
        <Function test_snakemake_rule_filter>
        <Function test_snakemake_rule_show_diff>
        <Function test_snakemake_rule_show_coords>
      <Module test_snakemake_fastani_workflow.py>
        <Function test_snakemake_rule_fastani>
    <Module test_tools.py>
      <Function test_bad_path_missing>
      <Function test_bad_path>
      <Function test_bad_binary_name>
      <Function test_non_exec>
      <Function test_fake_blastn>
      <Function test_fake_fastani>
      <Function test_fake_nucmer>
      <Function test_find_blastn>
      <Function test_find_fastani>
      <Function test_find_nucmer>

================= 17 tests collected in 0.93s ==================
```

I could easily merge some of the tool tests (e.g. all the ``test_bad_*`` could be one), but that doesn't seem important?

For the snakemake tests, I'd like to address the function name duplication between the anim and dnadiff modules...

**Comment by kiepczi** [comment]
Hi @peterjc,

It might have been a bad practice on my part, but I named the rules based on the output returned by the said rule. Although both the `anim` and `dnadiff` methods require the same output format, they differ in the parameters used to generate them. Let me quickly break this down for you.

`rule_delta` - Generates `.delta` files using `nucmer`. For `anim`, we currently use the `--mum` parameter, and for `dnadiff`, we use `--maxmatch`.  
`rule_filter` - Generates a `.filter` file using the `delta-filter` command, which either has the `-1` option for `anim` or the `-m` option for `dnadiff`.

Hope that's helpful.

**Comment by peterjc** [comment]
I'd lean to inserting ``anim`` or ``dnadiff`` into the rule names too.

**Comment by widdowquinn** [comment]
> I'd lean to inserting `anim` or `dnadiff` into the rule names too.

Are you thinking more maximalist, with `test_snakemake_anim_rule_filter()`? I was quite keen on allowing the hierarchy to imply what's happening, e.g.

`tests/snakemake/test_anim_workflow/test_rule_filter()`

I'm open to arguments in favour of a longer test name, though.

**Comment by peterjc** [comment]
My motivation was practical - how best to run specific tests when debugging something locally:

```
$ pytest -h
usage: pytest [options] [file_or_dir] [file_or_dir] [...]

positional arguments:
  file_or_dir

general:
  -k EXPRESSION         Only run tests which match the given substring expression. An
                        expression is a Python evaluable expression where all names are
                        substring-matched against test names and their parent classes.
                        Example: -k 'test_method or test_other' matches all test
                        functions and classes whose name contains 'test_method' or
                        'test_other', while -k 'not test_method' matches those that
                        don't contain 'test_method' in their names. -k 'not test_method
                        and not test_other' will eliminate the matches. Additionally
                        keywords are matched to classes and functions containing extra
                        names in their 'extra_keyword_matches' set, as well as
                        functions which have names assigned directly to them. The
                        matching is case-insensitive.
...
```

Globally unique long function names are easy to use with ``pytest -k function_name`` but actually looking closer this isn't such a problem using a combination of module name and function name. e.g.

```
$ pytest -v -k "test_snakemake_anim_workflow.py and test_snakemake_rule_delta"
================================= test session starts =================================
platform darwin -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0 -- /Users/xxx/mambaforge/envs/pyani-plus_py312/bin/python3.12
cachedir: .pytest_cache
rootdir: /Users/pc40583/repositories/pyani-plus
configfile: pyproject.toml
plugins: cov-5.0.0, xdist-3.6.1
collected 23 items / 22 deselected / 1 selected 
...
```

So on reflection, I'm OK with dropping the globally unique long function names idea.

**Comment by widdowquinn** [comment]
We should probably put these thoughts into the [design docs](https://github.com/pyani-plus/design-documentation)… I've been remiss, myself.

**Comment by kiepczi** [comment]
@peterjc, you’ve done amazing work in PR #193, where you refactored the entire structure of fixtures as well as cleaned up the `conftest.py`. Should we close this issue now?

**Comment by peterjc** [comment]
We should probably do some test documentation, e.g. a top-level README file in each of the fixture directories?

**Comment by kiepczi** [comment]
Sure, I can take care of this. Is there something in particular that you want? Are there any good examples out there that I can take inspiration from?

**Comment by peterjc** [comment]
Hmm. I was thinking short and sweet, a bit like the README files under https://github.com/peterjc/thapbi-pict/tree/master/examples for some worked examples, but here explaining what the test files are (e.g. three phage) and why (a minimal 'good' example which is quick for testing).

**Comment by kiepczi** [comment]
Can I close this issue? Documentation was added in #215.
