### ISSUE TITLE
Split `test_snakemake_slurm.py` into separate files by method

### ISSUE THREAD

**Issue by widdowquinn** [pyani-plus/pyani-plus#37]
## Summary:

Let's split `test_snakemake_slurm.py` into separate test files, by method.

## Description:

The current `test_snakemake_slurm.py` file includes tests for two methods, so a failure can ambiguous in the top level `pytest -v` output, it joins together tests for methods that are otherwise separate in the test suite, and it takes longer to run than other tests.

Splitting out `dnadiff` and `anim` tests into their own files would be an enhancement.

**Comment by peterjc** [comment]
i.e. https://github.com/pyani-plus/pyani-plus/blob/main/tests/snakemake/test_snakemake_slurm.py

Do you think this would be a good issue for me to try?

**Comment by widdowquinn** [comment]
I'd give it a few minutes. I was looking over #35 at @kiepczi's request and there may be a couple of changes merged to `main` shortly.

**Comment by widdowquinn** [comment]
There you go - I've merged #35 to fix #18 and that test file should be ready for refactoring.

**Comment by peterjc** [comment]
Note with the changes for #50 on #52 to skip the SLURM tests on GitHub actions, refactoring the SLURM tests will no longer have any impact on the GitHub Actions CI run-time.

**Comment by widdowquinn** [comment]
I think it would be neater, and I like neat ;) 🌈

**Comment by widdowquinn** [comment]
Removed in #61. Closing.
