### ISSUE TITLE
Document bioconda dependency in CONTRIBUTING

### ISSUE THREAD

**Issue by peterjc** [pyani-plus/pyani-plus#40]
Currently my machine has conda with just the conda-forge channel, meaning the instructions in https://github.com/pyani-plus/pyani-plus/blob/main/CONTRIBUTING.md failed when trying to install snakemake (which looks to be in bioconda only).

I note the GitHub action workflows currently uses ``channels: defaults,bioconda,conda-forge`` (where defaults is probably not needed anymore).

I'm inclined to opt for a minimal edit, adding a line like: "We assume you have conda setup with at least the conda-forge and bioconda channels."

**Comment by widdowquinn** [comment]
I think we should drop the `defaults` channel (and ensure everything still works).

Adding a rule to `Makefile` to set conda channels might be an idea?

**Comment by peterjc** [comment]
I'll try dropping the ``defaults`` channel on a pull request.

As a user, I'd be wary of my conda channels being changed behind my back (unless perhaps this can be isolated to the pyani environment - not sure about that).

**Comment by widdowquinn** [comment]
In my head, we'd be providing it - and the conda workarounds for arm64/x86 - as an optional `Makefile` rule. They'd be convenient for writing the CI workflow files, and conveniences for users who are in one of those situations. I don't think we should enforce either for all installs.

**Comment by peterjc** [comment]
I did wonder about the repetition between the makefile and the workflows. However, calling the makefile higher level targets from the workflow means we loose the useful subtasks in the workflow reporting. There could be a middle ground by having the workflow call the sub-targets within the makefile?

**Comment by widdowquinn** [comment]
I think that the value of detailed workflow reporting is greater, and we should preserve it so, OK, we keep the commands explicit there, despite the repetition?

We should have a reminder comment in each of the Makefile/workflow files to remind us to keep the bits and pieces in sync, maybe?
