### ISSUE TITLE
Missing conda packages for dependencies under osx-arm64

### ISSUE THREAD

**Issue by peterjc** [pyani-plus/pyani-plus#41]
Attempting to install the development environment as per the CONTRIBUTING file (cross reference #40), I ran into a problem:

```
PackagesNotFoundError: The following packages are not available from current channels:          
                                                                                                
  - mummer==3.23=h6de7cb9_11
  - gsl==2.7=h93259b0_0
  - fastani
  - blast-legacy
  - blast

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/bioconda
```

This was under macOS with an M3 ARM CPU (``Platform: osx-arm64``).

As per https://github.com/bioconda/bioconda-recipes/issues/33333#issuecomment-2221176852 last month, BioConda packages can be updated to cover this platform. I fear mummer and gsl will be problematic given these are pinned to specific (older) builds though. Also BLAST has quite a few dependencies which are not yet all updated.

**Comment by widdowquinn** [comment]
Ah yes - @kiepczi found this problem on her Mac Studio. We should provide instructions to get around this, as your suspicion around MUMmer seems to be correct.

Everything does run under Rosetta, but you now may need to explicitly install this, as it wasn't there by default on her machine. She also specified the use of x86 for her conda environment.

This issue also limits our use of the most recent macOS platform in GitHub Actions, which is arm64. So it would be nice to have the necessary groundwork in scripted form.

**Comment by peterjc** [comment]
There may be issues with the "successfully" installed packages too, ``python -m pytest -v`` is failing multiple tests with:

``OSError: [Errno 86] Bad CPU type in executable: '/Users/peterjc/miniforge3/envs/pyani-plus_py312/lib/python3.12/site-packages/pulp/solverdir/cbc/osx/64/cbc'``

The error appears to be correct:

```
$ file /Users/peterjc/miniforge3/envs/pyani-plus_py312/lib/python3.12/site-packages/pulp/solverdir/cbc/osx/64/cbc
/Users/peterjc/miniforge3/envs/pyani-plus_py312/lib/python3.12/site-packages/pulp/solverdir/cbc/osx/64/cbc: Mach-O 64-bit executable x86_64
```

```
$ file `which cbc`
/Users/peterjc/miniforge3/envs/pyani-plus_py312/bin/cbc: Mach-O 64-bit executable arm64
```

```
$ conda list | grep pulp
pulp                      2.8.0           py312h81bd7bf_0    conda-forge
```

There do seem to be platform specific packages on https://anaconda.org/conda-forge/pulp/files so perhaps the cross compilation failed?

See https://github.com/conda-forge/pulp-feedstock/blob/main/recipe/meta.yaml

**Comment by widdowquinn** [comment]
Sounds like you need the same fixes that @kiepczi did :(

- https://support.apple.com/en-us/102527
- https://stackoverflow.com/questions/65415996/how-to-specify-the-architecture-or-platform-for-a-new-conda-environment-apple

were useful IIRC.

**Comment by peterjc** [comment]
Installing Rosetta does sound like a pragmatic short-term workaround, but I think the pieces are all there *in principle* to get the dependencies updated in conda-forge and bioconda. Indeed I would expect many of the BioConda packages to be updated by the community anyway in the next few months...

**Comment by widdowquinn** [comment]
We've been waiting for the `mummer=3.23=h6de7cb9_11` not to be required for a long time. It would definitely be pragmatic to put a fix in place… (and maybe look at mummer4)

https://github.com/bioconda/bioconda-recipes/issues/28209

**Comment by peterjc** [comment]
The mummer issue is resolved 🥳 

I did some more digging on the snakemake/pulp issue - see https://github.com/snakemake/snakemake/issues/3007 and linked issues on the conda package and the upstream repository. They added Linux ARM support recently so fingers crossed for macOS ARM support to follow.

**Comment by peterjc** [comment]
We now also have osx-arm64 for fastani in bioconda: https://github.com/bioconda/bioconda-recipes/pull/49911

**Comment by widdowquinn** [comment]
As noted on the PR discussion, I'd be happy to drop `blast-legacy` going forward. Its main use was ensuring consistency with other tools that have themselves moved on.
