### ISSUE TITLE
Explore `pytest-xdist` to run pytest in parallel

### ISSUE THREAD

**Issue by peterjc** [pyani-plus/pyani-plus#51]
See https://pypi.org/project/pytest-xdist/

We may need to restructure some of the tests to ensure they are atomic, particularly any which share output/intermediate folders (e.g. switch to using ``/tmp`` for those).

The GitHub Actions seem to offer 4 CPUs/threads.

**Comment by widdowquinn** [comment]
I'm hoping this will work well for unit tests - some of the longer whole-workflow/integration tests might need to be run "serially." We can probably split the two test groups with `pytest` markers.

**Comment by peterjc** [comment]
Sadly just installing this dependency and adding ``-n auto`` to the ``pytest`` command is not enough. This does run the tests in parallel but we get multiple somewhat cryptic failures. e.g. running with more cores than the current 13 tests on Linux:

```
$ pytest -n auto -v tests/ -k "no slurm"
===================================== test session starts ======================================
platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0 -- /home/pjacock/miniforge3/envs/pyani-plus_py312/bin/python3.12
...
=================================== short test summary info ====================================
FAILED tests/snakemake/test_snakemake_fastani_workflow.py::test_snakemake_rule_fastani - FileNotFoundError: [Errno 2] No such file or directory: '/home/pjacock/repositories/pyani-p...
FAILED tests/snakemake/test_snakemake_slurm.py::test_dnadiff_rule_delta_slurm - snakemake_interface_common.exceptions.WorkflowError: Error: Unlocking the directory /home/p...
FAILED tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_delta - snakemake_interface_common.exceptions.WorkflowError: Error: Unlocking the directory /home/p...
FAILED tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_delta - snakemake_interface_common.exceptions.WorkflowError: Error: Unlocking the directory /home/p...
FAILED tests/snakemake/test_snakemake_slurm.py::test_snakemake_rule_fastani_slurm - snakemake_interface_common.exceptions.WorkflowError: Error: Unlocking the directory /home/p...
FAILED tests/snakemake/test_snakemake_slurm.py::test_dnadiff_rule_show_diff_slurm - FileNotFoundError: [Errno 2] No such file or directory: '/home/pjacock/repositories/pyani-p...
FAILED tests/snakemake/test_snakemake_slurm.py::test_snakemake_rule_filter_slurm - snakemake_interface_common.exceptions.WorkflowError: Error: Unlocking the directory /home/p...
====================== 7 failed, 6 passed, 6 warnings in 62.83s (0:01:02) ======================
```

**Comment by widdowquinn** [comment]
I think the workflow tests might not be suitable for the parallel approach - but that's all we have implemented jsut now.

Let's keep `pytest-xdist` in our back pockets for unit tests as we build up parsing/database integration, and the CLI.

**Comment by peterjc** [comment]
For per-test temporary output directories, I was looking at using the Python ``tempfile`` module and thinking about how to do cleanup - then discovered https://docs.pytest.org/en/latest/how-to/tmp_path.html should take care of that for us.

It looks like most (all?) of the snakemake failures are to do with locking, 

```
E           snakemake_interface_common.exceptions.WorkflowError: Error: Unlocking the directory /Users/pc40583/repositories/pyani-plus failed. Maybe you don't have the permissions?
E           FileNotFoundError: [Errno 2] No such file or directory: '/Users/pc40583/repositories/pyani-plus/.snakemake/locks'

../../mambaforge/envs/pyani-plus_py312/lib/python3.12/site-packages/snakemake/workflow.py:838: WorkflowError
```

That could be as simple as running snakemake in a temporary working directory each time, rather than the current directory?

**Comment by widdowquinn** [comment]
> For per-test temporary output directories, I was looking at using the Python `tempfile` module and thinking about how to do cleanup - then discovered https://docs.pytest.org/en/latest/how-to/tmp_path.html should take care of that for us.

Aye - `pytest` is really comprehensive and tends to have most things we can think of covered 😄

**Comment by peterjc** [comment]
I think changing the output directories of each test to use ``tmp_path`` makes sense, but it means refactoring many of the fixtures like the configuration dictionaries which include this as ``"outdir"``. Possibly via https://docs.pytest.org/en/stable/how-to/fixtures.html#fixtures-can-introspect-the-requesting-test-context to get the current path to use for ``"outdir"``?

**Comment by widdowquinn** [comment]
Could we use a single  `pytest` temporary path for the pytest run output, defined in `conftest.py` and extended in the existing fixtures, rather than writing to a local directory under `tests`? Or am I misunderstanding the issue?

**Comment by widdowquinn** [comment]
Something like:

```python
@pytest.fixture()
def anim_nucmer_targets_filter_outdir(tmpdir) -> Path:
    """Output directory for MUMmer filter snakemake tests.

    This path indicates the location to which MUMmer should write
    its output files during ANIm testing
    """
    return tmpdir / "outputs" / "nucmer_filter_output"
```

**Comment by peterjc** [comment]
Essentially yes (although ``tmp_path`` is the fixture name they used https://docs.pytest.org/en/stable/how-to/tmp_path.html#the-tmp-path-fixture).

I was thinking a new temp path for each test to ensure isolation, but *if* we have distinct named subdirectories, that isn't needed.

**Comment by peterjc** [comment]
I spent most of today trying to get the snakemake tests to work with a custom working directory (wanting to use different temp directories for parallel testing). Doing so means relative paths in the inputs and outputs are no longer relative to the repository:

https://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-does-snakemake-interpret-relative-paths

This seems to mean making the inputs absolute, and a choice of absolute output directories (under temp as per #56), or relative directories (under the temp working directory).

**Comment by peterjc** [comment]
I just updated the https://github.com/pyani-plus/pyani-plus/tree/issue_51 branch with the initial commit (addressing a merge conflict), and as expected it fails on macOS with locking issues (4 workers) but surprisingly the Linux test passed (2 workers). Remember this is the non-SLURM tests only. Perhaps simply with less workers there was less chance of conflict?

Note the GitHub Actions runtime was not dramatically different on macOS (4 workers, about 14 or 15 mins - perhaps a minute quicker assuming the computations actually all ran), but is now slower on Linux (2 workers, took about 14 to 15 mins, up from 8 to 9 mins without parallelization).

This may be far more useful for local development where we have access to significantly more cores.
