### ISSUE TITLE
Consider reducing test dataset sizes

### ISSUE THREAD

**Issue by widdowquinn** [pyani-plus/pyani-plus#63]
## Summary:

In the old `pyani` we used _Blochmannia_ genome example datasets (among other things), and moving to `pyani-plus` gives us an opportunity to update our choices to reduce test run time and target particular known (prior) issues.

For example, we could introduce Donovan Parks' virus sequences (https://github.com/widdowquinn/pyani/issues/340), which would allow us to simultaneously reduce input test dataset size and confirm that our fixes for the coverage problem continue to work (and validate ANIm/other tests).

**Comment by widdowquinn** [comment]
We may want to consider dividing tests of datasets into groups (e.g. "fast" and "slow"; "viral", "bacterial", "linear genomes") etc. and running these on different schedules. For example:

- "fast" tests would run in CI on a `push`
- "slow" tests would run in CI on a PR merge
- "complete" tests might run monthly on CI/locally when being particularly paranoid about a change.

**Comment by peterjc** [comment]
See e.g. https://docs.pytest.org/en/7.1.x/example/markers.html#registering-markers which uses marking some tests as "slow" for example.

**Comment by widdowquinn** [comment]
This would help avoid the current duplicate `push` and `pull-request` GH Action runs we have at the moment. Running the "fast" tests only on `push` and the "slow"/"complete" tests on `pull-request` would be a useful, meaningful separation of the two activities.
